---
- hosts: localhost
  connection: local
  become: true  

  tasks:
  - name: copy 70-persistent-net.rules
    tags: ap
    copy:
      src: files/70-persistent-net.rules
      dest: /etc/udev/rules.d/70-persistent-net.rules
      owner: root
      group: root

  - name: install packages
    tags: ap
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - dnsmasq
      - hostapd

  - name: copy dnsmasq.conf
    tags: ap
    copy:
      src: files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root

  - name: copy hostapd.conf
    tags: ap
    copy:
      src: files/hostapd.conf
      dest: /etc/hostapd/hostapd.conf
      owner: root
      group: root