---
- hosts: localhost
  connection: local
  become: true  
  vars:
    wlan0_mac: "b8:27:eb:ff:ff:ff"
    ap0_mac: "b8:27:eb:ff:ff:00"
    ap0_ip: "192.168.99.254"
    bssid_mac: "b8:27:eb:ff:ff:00"
    dhcp_clients: #dnsmasq static cliensts
      - mac: "b8:27:eb:ff:ff:01"
        ip: "192.168.99.1"
        name: client1
      - mac: "b8:27:eb:ff:ff:02"
        ip: "192.168.99.2"
        name: client2

  tasks:
  - name: disable ipv6
    tags: ipv6
    import_tasks: disableipv6.yml

  - name: copy 70-persistent-net.rules
    tags: ap
    copy:
      src: files/70-persistent-net.rules
      dest: /etc/udev/rules.d/70-persistent-net.rules
      owner: root
      group: root

  - name: install packages
    tags: test
    package:
      name: "{{ item }}"
      state: latest
    with_items:
      - dnsmasq
      - hostapd

  - name: copy dnsmasq.conf
    tags: test
    copy:
      src: files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root

  - name: copy hostapd.conf
    tags: test
    copy:
      src: files/hostapd.conf
      dest: /etc/hostapd/hostapd.conf
      owner: root
      group: root